address_id: 718
baseURL: "http://jxair.minhopeonline.com//prod-api/"
token: "eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImZjODMxODQ4LTQwYzgtNDY5ZS1hYjdjLTkxMmVlYWI4MWIxMCJ9.Oybh7Gdtvki0rop9O5xnBzUZvhEeqMLODLBXxqcpMEcdIMIjkgEoAPaw_8puQLDsHG_1keL1KQwhorB7F06ccQ"
gettoken: 6095
case_data_path: /data/single_data_v1.0/
get_sign_url: /test/get/sign
headers:
  Authorization: MTIzOnJvb3Q=
  Content-Type: application/json
  User-Agent: PostmanRuntime/7.28.4
device_register_url: /device/register
device_sign_url: /device/sign
User-Agent:
  channel: appStore
  deviceModel: iPhone
  deviceToken: 12312-232
  platform: iOS
  sysVersion: 14.7.1
  appName: mimu
  appVersion: '1.2'
  network: 4G
